"""init base schema

Revision ID: 7e69e0feb4b8
Revises: 
Create Date: 2025-10-23 17:10:34.001855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e69e0feb4b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('goal_type', sa.Enum('maintain', 'lose', 'gain', 'eat_healthy', name='goaltype'), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('calories_kcal', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('sugar_g', sa.Integer(), nullable=True),
    sa.Column('fiber_g', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_created_at'), 'goal', ['created_at'], unique=False)
    op.create_index(op.f('ix_goal_user_id'), 'goal', ['user_id'], unique=False)
    op.create_table('meallog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('eaten_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('sugar_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meallog_eaten_at'), 'meallog', ['eaten_at'], unique=False)
    op.create_index(op.f('ix_meallog_user_id'), 'meallog', ['user_id'], unique=False)
    op.create_table('onboardingsubmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('goal_type', sa.Enum('maintain', 'lose', 'gain', 'eat_healthy', name='goaltype'), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('counted_calories_before', sa.Boolean(), nullable=True),
    sa.Column('training_frequency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('steps_per_day', sa.Integer(), nullable=True),
    sa.Column('work_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('promo_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('app_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Integer(), nullable=True),
    sa.Column('fat_g', sa.Integer(), nullable=True),
    sa.Column('carbs_g', sa.Integer(), nullable=True),
    sa.Column('fiber_g', sa.Integer(), nullable=True),
    sa.Column('sugar_g', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboardingsubmission_submitted_at'), 'onboardingsubmission', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_onboardingsubmission_user_id'), 'onboardingsubmission', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('start_weight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('current_goal_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_current_goal_id'), 'user', ['current_goal_id'], unique=False)
    op.create_table('waterlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drank_at', sa.DateTime(), nullable=False),
    sa.Column('ml', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waterlog_drank_at'), 'waterlog', ['drank_at'], unique=False)
    op.create_index(op.f('ix_waterlog_user_id'), 'waterlog', ['user_id'], unique=False)
    op.create_table('weightlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weightlog_on_date'), 'weightlog', ['on_date'], unique=False)
    op.create_index(op.f('ix_weightlog_user_id'), 'weightlog', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weightlog_user_id'), table_name='weightlog')
    op.drop_index(op.f('ix_weightlog_on_date'), table_name='weightlog')
    op.drop_table('weightlog')
    op.drop_index(op.f('ix_waterlog_user_id'), table_name='waterlog')
    op.drop_index(op.f('ix_waterlog_drank_at'), table_name='waterlog')
    op.drop_table('waterlog')
    op.drop_index(op.f('ix_user_current_goal_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_onboardingsubmission_user_id'), table_name='onboardingsubmission')
    op.drop_index(op.f('ix_onboardingsubmission_submitted_at'), table_name='onboardingsubmission')
    op.drop_table('onboardingsubmission')
    op.drop_index(op.f('ix_meallog_user_id'), table_name='meallog')
    op.drop_index(op.f('ix_meallog_eaten_at'), table_name='meallog')
    op.drop_table('meallog')
    op.drop_index(op.f('ix_goal_user_id'), table_name='goal')
    op.drop_index(op.f('ix_goal_created_at'), table_name='goal')
    op.drop_table('goal')
    # ### end Alembic commands ###
